id: P004277
initial_creation_type: ocr
source_metadata:
  id: bdr:W29297
  title: ཕྱི་རྒྱལ་གྱི་ཚད་མ་རིག་པའི་ཞིབ་འཇུག
  author: ''
  volumes:
    3d3d3e8c1a3b443489d5d87f39b0ac79:
      image_group_id: I1KG10488
      title: ''
      volume_number: 1
      total_pages: 247
